version: 0.0
os: linux
files:
   - source: /source/
     destination: /var/www/html
     overwrite: RETAIN
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 777
     type:
       - directory
